module.exports = {
    tailwindConfig: './tailwind.config.ts',
    endOfLine: 'lf',
    semi: false,
    singleQuote: true,
    tabWidth: 4,
    printWidth: 120,
    trailingComma: 'es5',
    importOrder: [
        '^(react/(.*)$)|^(react$)',
        '^(next/(.*)$)|^(next$)',
        '<THIRD_PARTY_MODULES>',
        '',
        '^types$',
        '^@/types/(.*)$',
        '^@/config/(.*)$',
        '^@/lib/(.*)$',
        '^@/hooks/(.*)$',
        '^@/components/ui/(.*)$',
        '^@/components/(.*)$',
        '^@/styles/(.*)$',
        '^@/app/(.*)$',
        '',
        '^[./]',
        '^@/src/(.*)$',
        '^@/src/components/(.*)$',
        '@/src/app/(.*)$',
    ],
    importOrderBuiltinModulesToTop: true,
    importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
    plugins: ['@ianvs/prettier-plugin-sort-imports'],
    importOrderCombineTypeAndValueImports: true,
    importOrderMergeDuplicateImports: true,
    importOrderSortSpecifiers: true,
    importOrderSeparation: false,
    tailwindFunctions: ['cva'],
}
